### ISSUE TITLE
Fullscreen doesn't function.

### ISSUE THREAD

**Issue by ChaosPA** [ChaosPA/pristontale#14]
After the recent changes to the widescreen function we've messed up the fullscreen mode.

**Comment by Naaliss** [comment]
I can use fullcreen mode doing theses change in ptreg
"ScreenSize" "1"
"FullMode" "on"

Full ptreg if it can help

"Server1" "83.128.56.65"
"Server2" "83.128.56.65"
"Server3" "83.128.56.65"
"Version" "3130"
"ServerName" "ORIGIN"
"Graphic" "0"
"ColorBPP" "32"
"Network" "1"
"CameraInvert" "false"
"MotionBlur" "false"
"CameraSight" "on"
"ScreenSize" "1"
"Sound" "off"
"FullMode" "on"
"MicOption" "off"
"RainMode" "off"
"Account" "naalis"

**Comment by ChaosPA** [comment]
Resolved.
