### ISSUE TITLE
Wide screen client

### ISSUE THREAD

**Issue by neosaldina** [ChaosPA/pristontale#8]
Add more cases to support every new calculations for widescreen support

**Comment by neosaldina** [comment]
Wide screen implemented...
Any bugs, I will leave this issue closed, but, opened for comments or any bug report 

![untitled](https://user-images.githubusercontent.com/36016660/35716848-98de49b8-07c2-11e8-9828-cd255814e62c.png)

**Comment by neosaldina** [comment]
live bar size fixed

![image](https://user-images.githubusercontent.com/36016660/35717660-d25debc6-07c7-11e8-8ecf-6009699dab60.png)

**Comment by ChaosPA** [comment]
I've found a issue in character creation: 
http://prntscr.com/i92riz

**Comment by bencz** [comment]
Ok, I will look for this
